# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('records', '0001_initial'), ('records', '0002_record_letter'), ('records', '0003_auto_20150321_1246'), ('records', '0004_auto_20150322_0543'), ('records', '0005_auto_20150426_1426'), ('records', '0006_auto_20150503_1741')]

    dependencies = [
        ('cases', '0016_auto_20150316_0931'),
        ('events', '0004_auto_20150322_0543'),
        ('contenttypes', '0001_initial'),
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('letter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='letters.Letter')),
                ('alarm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Alarm')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('created_on', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 4, 26, 21, 26, 57, 237045, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ['created_on', 'id'],
            },
        ),
    ]
