# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_record_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
