language: python
python:
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

env:
  fast_finish: true
  global:
    - DATABASE_URL="mysql://root:@localhost/poradnia"
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=py27-dj111-coveralls
    - TOX_ENV=py35-dj111-coveralls
    - TOX_ENV=py35-djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=py35-djmaster

before_install:
  - .contrib/travis-ci/create-database.sh
install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV

notifications:
  slack: watchdogpolska:mQq180xGu9UcuJgK73hVWECD

after_script:
- rm $HOME/.cache/pip/log/*
