language: python
python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

env:
  fast_finish: true
  global:
    - DATABASE_URL="mysql://root:@localhost/test_poradnia"
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=dj110-coveralls
    - TOX_ENV=dj111-coveralls
    - TOX_ENV=dj20-coveralls
    - TOX_ENV=djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=dj20-coveralls
    - env: TOX_ENV=djmaster

install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV

notifications:
  slack: watchdogpolska:mQq180xGu9UcuJgK73hVWECD

after_script:
- rm $HOME/.cache/pip/log/*
