# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 15:44
from __future__ import unicode_literals

import django_bleach.models
from django.db import migrations
from django.db.models import F, Func, Value


class Replace(Func):
    """
    An SQL function call.
    """
    function = 'replace'
    template = '%(function)s(%(expressions)s)'

    def __init__(self, *expressions, **extra):
        super(Replace, self).__init__(*expressions, **extra)
        if len(expressions) != 3:
            raise ValueError('expressions must have a three elements')


def forwards_func(apps, schema_editor):
    Letter = apps.get_model("letters", "letter")
    db_alias = schema_editor.connection.alias
    text = F('text')
    text = Replace(text, Value("\n\n"), Value("\n"))
    text = Replace(text, Value("\n"), Value("<br>"))
    Letter.objects.using(db_alias).update(text=text)


def reverse_func(apps, schema_editor):
    Letter = apps.get_model("letters", "letter")
    db_alias = schema_editor.connection.alias
    text = F('text')
    text = Replace(text, Value("<br>"), Value("\n"))
    Letter.objects.using(db_alias).update(text=text)


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_auto_20160409_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=django_bleach.models.BleachField(verbose_name='Text'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
