# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('stats', '0001_initial'), ('stats', '0002_auto_20170804_0321'), ('stats', '0003_auto_20170804_0413'), ('stats', '0004_auto_20170804_1947'), ('stats', '0005_auto_20170805_1307')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(db_index=True, max_length=50, verbose_name='Metric key')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('last_updated', models.DateTimeField(verbose_name='Time to get the last value')),
            ],
            options={
                'ordering': ['key'],
                'verbose_name': 'key',
                'verbose_name_plural': 'keys',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('comment', models.CharField(max_length=150)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Item')),
            ],
            options={
                'ordering': ['item_id', 'time'],
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time to get the last value'),
        ),
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=True, help_text='Select to publish metric for everyone on-line.', verbose_name='Public?'),
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Graph',
                'verbose_name_plural': 'Graphs',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['key'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='graph',
            name='items',
            field=models.ManyToManyField(to='stats.Item', verbose_name='Items'),
        ),
    ]
