# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poradnia.keys.utils


class Migration(migrations.Migration):

    replaces = [('keys', '0001_initial'), ('keys', '0002_auto_20150710_2133'), ('keys', '0003_auto_20150721_0232')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default=poradnia.keys.utils.make_random_password, max_length=75, verbose_name='Key')),
                ('description', models.CharField(max_length=75, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('used_on', models.DateTimeField(null=True, verbose_name='Used on')),
                ('download_on', models.DateTimeField(null=True, verbose_name='Download on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access key',
                'verbose_name_plural': 'Access keys',
            },
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together=set([('user', 'password')]),
        ),
    ]
